<?php

/**
 * Implementation of hook_menu().
 */
function idm_support_menu() {
  $items = array ();
  $items['support'] = array (
    'title' => 'Support',
    'page callback' => '_idm_support_list_support',
    'access arguments' => array('access idm profile')
  );

  return $items;
}


/**
 * Callback for Support.
 */
function _idm_support_list_support() {
  $content['info'] = array (
    '#type' => 'markup',
    '#markup' => _idm_support_get_support(),
    '#suffix' => '<div class="clr"></div>'
  );
  return $content;
}
/**
 * Implementing hook_theme().
 */
function idm_support_theme() {
  $themes = array (
	'support' => array (
      'template' => 'support',
      'variables' => array (
        'vars' => array (
          ''
        )
      )
    ),
  );
  return $themes;
}
function _idm_support_get_support() {
	$var = array();
	return theme('support', $var);
}
